name: Build & Deploy

on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 8 * * *'

jobs:
  build-deploy:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v2
    
    - name: Use Node.js
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'
    
    - name: Install dependencies
      run: npm install

    - name: Build
      run: GITHUB_ACCESS_TOKEN=${{ secrets.GITHUB_ACCESS_TOKEN }} npm run build

    - name: Deploy
      uses: peaceiris/actions-gh-pages@v3
      with:
        personal_token: ${{ secrets.GITHUB_ACCESS_TOKEN }}
        publish_dir: ./public
        emptyCommits: false
